using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;

const string ApiUrl = "https://pm.preprod.parking.scheidt-bachmann.net/capacity-manager/v2/de_studentui/occupancy/facilities";
const string ApiToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1YkhqdDlHWFYwVnZGbEx2eXBzc1E2aHdWN2xHVDYwSThsWlJJdWZnMnlFIn0.eyJleHAiOjE3NzY4NDYxOTAsImlhdCI6MTc3Njg0NDM5MCwianRpIjoidHJydGNjOjA0ZmQzY2M3LTYyNDEtYzc0MS05NWZiLTlkMGUzYjY2ZDMwZCIsImlzcyI6Imh0dHBzOi8vYXV0aC5wcmVwcm9kLnBhcmtpbmcuc2NoZWlkdC1iYWNobWFubi5uZXQvYXV0aC9yZWFsbXMvZGVfc3R1ZGVudHVpIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImVjNjU0NTVmLWMwMjYtNGQ4My1hNWYwLTgwNzhlOWY5Y2M0NiIsInR5cCI6IkJlYXJlciIsImF6cCI6IkIyQ19kZV9zdHVkZW50dWkiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLWRlX3N0dWRlbnR1aSIsIkFQSSBVc2VyIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiYWRkcmVzcyBlbWFpbCBwcm9maWxlIG9mZmxpbmVfYWNjZXNzIG1pY3JvcHJvZmlsZS1qd3QgcGhvbmUiLCJ1cG4iOiJzZXJ2aWNlLWFjY291bnQtYjJjX2RlX3N0dWRlbnR1aSIsImNsaWVudEhvc3QiOiIyMTMuODEuMTgyLjEzMCIsImFkZHJlc3MiOnt9LCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImdyb3VwcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtZGVfc3R1ZGVudHVpIiwiQVBJIFVzZXIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtYjJjX2RlX3N0dWRlbnR1aSIsImNsaWVudEFkZHJlc3MiOiIyMTMuODEuMTgyLjEzMCIsImNsaWVudF9pZCI6IkIyQ19kZV9zdHVkZW50dWkifQ.GmXr1-OFU23HM8zoSi-Yf_0QJBWPE0MFu2LywKa3V9mcgQ3v7xnKhpjWhHRSOfXjyFgt9CYxAYDgoUwYACJP4CJSh4uFmoe5WBWYGZj7JWUgohxJoVO00vZJXuHNhStjnwz5W9mLgaJm4QeG_CSmhUr6VLtym98Lk_fw3iBjUpS60zGm-_qUh9NATVUTPJBe2KlbbgazbAE2LWchvMOtlksHtX-xPpUQobMI0i3BLYF_gH_ov4xO1W019iMMKCfzj9JPxvlVxA4hxALkYNGoT2SRReJx-By7WDb9dUHfw0O4GcdPy3qdE4lRQxmp0nVPQQzqkx-Cf2RFM5rHbm--7Q";

using var client = new HttpClient();

client.DefaultRequestHeaders.Authorization =
    new AuthenticationHeaderValue("Bearer", ApiToken);

client.DefaultRequestHeaders.Accept.Add(
    new MediaTypeWithQualityHeaderValue("application/json")
);

Console.WriteLine("Calling REST API...");

HttpResponseMessage response = await client.GetAsync(ApiUrl);
Console.WriteLine($"Status: {response.StatusCode}");

response.EnsureSuccessStatusCode();

string json = await response.Content.ReadAsStringAsync();

Console.WriteLine("Raw JSON response:");
Console.WriteLine(json);
Console.WriteLine("-----------------------------");

